#!/bin/bash
# http://www.thegeekstuff.com/2009/07/linux-apache-mod-ssl-generate-key-csr-crt-file
openssl genrsa -des3 -out jupyterhub.key 1024
openssl req -new -key jupyterhub.key -out jupyterhub.csr
openssl x509 -req -days 3650 -in jupyterhub.csr -signkey jupyterhub.key -out jupyterhub.crt

